# Generated by Django 4.2.6 on 2023-11-21 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('pagina_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.paginaweb')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.JSONField()),
                ('tagged', models.JSONField()),
                ('summary', models.TextField()),
                ('parrafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.parrafo')),
            ],
        ),
    ]
